trigger:
  branches:
    include:
    - '*'
variables:
  system_accesstoken: $(GitOnAzure)

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true    #Allow scripts to access the system token
  clean: true 

- task: shellexec@0
  inputs:
    code: |
      git config --global user.email "krystel.menot@gmail.com"
      git config --global user.name "Ysikael"
      git branch -r | grep -v '\->' | while read remote; do git branch --track "${remote#origin/}" "$remote"; done
      git push https://$(GitOnAzure)@dev.azure.com/LittleBigPlanet/_git/LittleBigPlanetRepository.git -u --all
